name: Frontend Deploy Automation

on:
  push:
    branches:
      - main
    paths:
      - "dashboard/*"
  workflow_dispatch:
jobs:
  pull:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
  install_and_build:
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        working-directory: dashboard
        run: yarn install
      - name: Build
        run: yarn build
  upload_container:
    runs-on: self-hosted
    steps:
      - name: Stop Container
        run: docker compose down -v
      - name: Start Container
        run: docker compose up -d
