name: Frontend Deploy Automation

on:
  push:
    branches:
      - main
    paths:
      - "dashboard/*"
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check Repository Contents
         run: ls -lR
      - name: Change Directory
        working-directory: ./dashboard
        run: cd ./dashboard
      - name: Docker Compose Up
        run: docker compose up
