name: Frontend Deploy Automation

on:
  push:
    branches:
      - main
    paths:
      - "dashboard/*"
  workflow_dispatch:
jobs:
  pull:
    name: Pulling from repo
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
  install_and_build:
    runs-on: self-hosted
    name: Install deps and build
    needs: pull
    steps:
      - name: Install dependencies
        working-directory: dashboard
        run: yarn install
      - name: Build
        working-directory: dashboard
        run: yarn build
  upload_container:
    runs-on: self-hosted
    name: Update Container
    needs: install_and_build
    steps:
      - name: Stop Container
        working-directory: dashboard
        run: docker compose down -v
      - name: Start Container
        working-directory: dashboard
        run: docker compose up -d --force-recreate --renew-anon-volumes
