name: Frontend Deploy Automation

on:
  push:
    branches:
      - main
    paths:
      - "dashboard/*"
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Docker Compose Up
        working-directory: dashboard
        run: docker compose up
