name: Frontend Deploy Automation

on:
  push:
    branches:
      - main
    paths:
      - "dashboard/*"
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: git pull origin main
      - working-directory: ./dashboard
        run: docker compose up
