name: Frontend Deploy Automation

on:
  push:
    branches:
      - main
    paths:
      - "dashboard/*"
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: ls
      - run: docker compose up
