name: "Frontend Deploy Automation"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "dashboard/*"
  jobs:
    build:
      runs-on: self-hosted
      steps:
        - run: cd ./dashboard
        - run: docker compose up
