stages:
  - build-backend
  - build-frontend

build-backend:
  stage: build-backend
  only:
    changes:
      - ./backend/*

build-frontend:
  stage: build-frontend
  only:
    changes:
      - ./dashboard/*
  script:
    - cd ./dashboard
    - docker compose up
